"""DPO (Direct Preference Optimization) training for Gemma 2 2B.

Loads the SFT-merged model, applies QLoRA, and trains with DPO on the
preference dataset generated by create_preference_data.py.

Usage:
    python -m gemma2b.train_dpo
    python -m gemma2b.train_dpo --base models/base --sft-model models/sft_local/merged
    python -m gemma2b.train_dpo --epochs 2 --lr 5e-5
"""
from __future__ import annotations

import argparse
import json
import os

import torch
from datasets import Dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from trl import DPOConfig, DPOTrainer


def load_preference_data(path: str) -> Dataset:
    """Load preference JSONL into a HuggingFace Dataset."""
    examples = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            ex = json.loads(line)
            examples.append({
                "prompt": ex["prompt"],
                "chosen": ex["chosen"],
                "rejected": ex["rejected"],
            })
    return Dataset.from_list(examples)


def get_device(requested: str | None) -> torch.device:
    if requested:
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def main():
    parser = argparse.ArgumentParser(description="DPO training for Gemma 2B")
    parser.add_argument("--sft-model", type=str, default="models/sft_local/merged",
                        help="Path to SFT-merged model")
    parser.add_argument("--base", type=str, default="models/base",
                        help="Path to base model (unused if sft-model is merged)")
    parser.add_argument("--data", type=str, default="data/preference_train.jsonl")
    parser.add_argument("--output", type=str, default="models/dpo_local/adapter")
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--grad-accum", type=int, default=4)
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--beta", type=float, default=0.1,
                        help="DPO beta (controls divergence from reference)")
    parser.add_argument("--max-length", type=int, default=512)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--device", type=str, default=None)
    args = parser.parse_args()

    device = get_device(args.device)
    print(f"Device: {device}")
    print(f"SFT model: {args.sft_model}")

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.sft_model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    # Load model
    use_bnb = device.type == "cuda"
    attn_impl = "eager" if device.type == "mps" else "sdpa"

    if use_bnb:
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            args.sft_model,
            quantization_config=bnb_config,
            torch_dtype=torch.bfloat16,
            attn_implementation=attn_impl,
        )
        model = prepare_model_for_kbit_training(model)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            args.sft_model,
            torch_dtype=torch.float32,
            attn_implementation=attn_impl,
        )

    # Apply LoRA
    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_r * 2,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)

    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"Trainable: {trainable:,} / {total:,} ({100 * trainable / total:.2f}%)")

    # Load dataset
    dataset = load_preference_data(args.data)
    print(f"Loaded {len(dataset)} preference pairs")

    # DPO training config
    output_dir = args.output
    training_args = DPOConfig(
        output_dir=output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        beta=args.beta,
        max_length=args.max_length,
        precompute_ref_log_probs=True,
        logging_steps=10,
        save_strategy="epoch",
        remove_unused_columns=False,
        bf16=use_bnb,
        fp16=False,
        gradient_checkpointing=True,
        report_to="none",
        optim="adamw_torch",
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
    )

    trainer = DPOTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        processing_class=tokenizer,
    )

    print(f"\nStarting DPO training: {args.epochs} epoch(s), "
          f"batch={args.batch_size}x{args.grad_accum}, lr={args.lr}, beta={args.beta}")
    trainer.train()

    # Save
    os.makedirs(output_dir, exist_ok=True)
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"\nDPO adapter saved to {output_dir}")


if __name__ == "__main__":
    main()
